# Generated by Django 2.0.8 on 2019-07-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('1', '总监'), ('2', '经理'), ('3', '研发')], default='developer', max_length=32),
        ),
    ]
