# Generated by Django 2.0.8 on 2019-06-17 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idc',
            options={},
        ),
    ]
