# Generated by Django 2.0.8 on 2019-06-18 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20190617_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True)),
                ('remark', models.TextField()),
                ('number', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='编号')),
                ('size', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='尺寸')),
                ('idc', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='cmdb.Idc', verbose_name='所属机房')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
