# Generated by Django 2.0.8 on 2019-06-19 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_server'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='cpu',
            new_name='server_cpu',
        ),
        migrations.RenameField(
            model_name='server',
            old_name='disk',
            new_name='server_disk',
        ),
        migrations.RenameField(
            model_name='server',
            old_name='memory',
            new_name='server_memory',
        ),
    ]
