# Generated by Django 2.0.8 on 2019-06-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20190619_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='hostname',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='主机名'),
        ),
    ]
