# Generated by Django 2.0.8 on 2019-06-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0013_auto_20190620_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idc',
            name='remark',
            field=models.TextField(blank=True, default='', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='remark',
            field=models.TextField(blank=True, default='', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='server',
            name='remark',
            field=models.TextField(blank=True, default='', null=True, verbose_name='备注'),
        ),
    ]
