# Generated by Django 2.0.8 on 2019-06-26 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0014_auto_20190626_0552'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='idc',
            unique_together={('name',)},
        ),
    ]
