# Generated by Django 2.0.8 on 2019-06-29 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0015_auto_20190626_0604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idc',
            old_name='price',
            new_name='phone',
        ),
        migrations.AlterUniqueTogether(
            name='rack',
            unique_together={('name', 'idc')},
        ),
    ]
